name: e2e_tests
description: A e2e tests project for the bucketeer_flutter_client_sdk.
publish_to: 'none'

version: 1.1.0+1

environment:
  sdk: '>=2.15.0 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  bucketeer_flutter_client_sdk:
    path: ../

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mocktail: ^0.3.0

flutter:
  uses-material-design: true
